name: .NET Web API CI

on:
  push:
    branches:
      - main  # adjust to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # adjust to the desired .NET version

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test FreelanceApp.Tests/FreelanceApp.Tests.csproj --configuration Release --no-build --verbosity normal
